### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by SamiAlghamdi** [Code-Over-Time/varcade_games#57]
in the wiki in this section https://github.com/Code-Over-Time/varcade_games/wiki/get_the_code 

all of these don't work
![image](https://user-images.githubusercontent.com/68701542/219978074-6e35c73a-b247-4df9-a9cb-ae695e8a5a46.png)

this is what i get
![image](https://user-images.githubusercontent.com/68701542/219978131-a7be1e3a-6ad8-49a2-b0ae-4be6bbfdfe9a.png)

I checked "theblacknight" account and couldn't find the repos. 

Just wanted to point this out.
what I did to solve this is I cloned the whole repo and toke the files I needed. #

**Comment by Code-Over-Time** [comment]
Hey, thanks for reporting - looks like there was a conflict in the wiki and an older version of that page was being loaded. I have updated to the latest version. 

Thanks again!

- Kev
